### ISSUE TITLE
WissKI 

### ISSUE THREAD

**Issue by sepastian** [WissKI/wisski#2]
I am trying to install WissKI in Drupal8/PHP5 using Docker.

I am following your [instructions](http://wiss-ki.eu/installation_guide#From%20Drupal%208%20to%20a%20basic%20WissKI%20system), but I am receiving the following error when enabling the WissKI plugins:

```
wisski_1    | [Tue Jan 24 14:35:18.537308 2017] [:error] [pid 23] [client 132.231.71.104:41048] Recoverable fatal error: Argument 2 passed to Drupal\\views\\EntityViewsData::__construct() must implement interface Drupal\\Core\\Entity\\Sql\\SqlEntityStorageInterface, instance of Drupal\\wisski_core\\WisskiStorage given, called in /var/www/html/core/modules/views/src/EntityViewsData.php on line 100 and defined in /var/www/html/core/modules/views/src/EntityViewsData.php on line 81 #0 /var/www/html/core/includes/bootstrap.inc(548): _drupal_error_handler_real(4096, 'Argument 2 pass...', '/var/www/html/c...', 81, Array)
#1 /var/www/html/core/modules/views/src/EntityViewsData.php(81): _drupal_error_handler(4096, 'Argument 2 pass...', '/var/www/html/c...', 81, Array)
#2 /var/www/html/core/modules/views/src/EntityViewsData.php(100): Drupal\\views\\EntityViewsData->__construct(Object(Drupal\\Core\\Entity\\ContentEntityType), Object(Drupal\\wisski_core\\WisskiStorage), Object(Drupal\\Core\\Entity\\EntityManager), Object(Drupal\\Core\\Extension\\ModuleHandler), Object(Drupal\\Core\\StringTranslation\\TranslationManager), Object(Drupal\\Core\\TypedData\\TypedDataManager))
#3 /var/www/html/core/lib/Drupal/Core/Entity/EntityTypeManager.php(249): Drupal\\views\\EntityViewsData::createInstance(Object(Drupal\\Core\\DependencyInjection\\Container), Object(Drupal\\Core\\Entity\\ContentEntityType))
#4 /var/www/html/core/lib/Drupal/Core/Entity/EntityTypeManager.php(238): Drupal\\Core\\Entity\\EntityTypeManager->createHandlerInstance('Drupal\\\\wisski_c...', Object(Drupal\\Core\\Entity\\ContentEntityType))
#5 /var/www/html/core/lib/Drupal/Core/Entity/EntityManager.php(118): Drupal\\Core\\Entity\\EntityTypeManager->getHandler('wisski_individu...', 'views_data')
#6 /var/www/html/core/modules/views/views.views.inc(168): Drupal\\Core\\Entity\\EntityManager->getHandler('wisski_individu...', 'views_data')
#7 [internal function]: views_views_data()
#8 /var/www/html/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('views_views_dat...', Array)
#9 /var/www/html/core/modules/views/src/ViewsData.php(245): Drupal\\Core\\Extension\\ModuleHandler->invoke('views', 'views_data')
#10 /var/www/html/core/modules/views/src/ViewsData.php(162): Drupal\\views\\ViewsData->getData()
#11 /var/www/html/core/modules/views/src/Plugin/ViewsHandlerManager.php(85): Drupal\\views\\ViewsData->get('node_field_data')
#12 /var/www/html/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(882): Drupal\\views\\Plugin\\ViewsHandlerManager->getHandler(Array, NULL)
#13 /var/www/html/core/modules/views/src/ViewExecutable.php(1030): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->getHandlers('sort')
#14 /var/www/html/core/modules/views/src/ViewExecutable.php(888): Drupal\\views\\ViewExecutable->_initHandler('sort', Array)
#15 /var/www/html/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2256): Drupal\\views\\ViewExecutable->initHandlers()
#16 /var/www/html/core/modules/views/src/ViewExecutable.php(1679): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->preExecute()
#17 /var/www/html/core/modules/views/src/ViewExecutable.php(1614): Drupal\\views\\ViewExecutable->preExecute(Array)
#18 /var/www/html/core/modules/views/src/Element/View.php(78): Drupal\\views\\ViewExecutable->executeDisplay('page_1', Array)
#19 [internal function]: Drupal\\views\\Element\\View::preRenderViewElement(Array)
#20 /var/www/html/core/lib/Drupal/Core/Render/Renderer.php(376): call_user_func(Array, Array)
#21 /var/www/html/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\\Core\\Render\\Renderer->doRender(Array, false)
#22 /var/www/html/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\\Core\\Render\\Renderer->render(Array, false)
#23 /var/www/html/core/lib/Drupal/Core/Render/Renderer.php(574): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->Drupal\\Core\\Render\\MainContent\\{closure}()
#24 /var/www/html/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))
#25 /var/www/html/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->prepare(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))
#26 /var/www/html/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->renderResponse(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))
#27 /var/www/html/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): Drupal\\Core\\EventSubscriber\\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#28 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(144): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent))
#29 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#30 /var/www/html/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#31 /var/www/html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#32 /var/www/html/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#33 /var/www/html/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#34 /var/www/html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#35 /var/www/html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#36 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#37 /var/www/html/core/lib/Drupal/Core/DrupalKernel.php(652): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#38 /var/www/html/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#39 {main}
```

What's going on here?

**Comment by WissKI** [comment]
The error is due to line 27 in wisski_core/src/Entity/WisskiEntity.php:
"views_data" = "Drupal\wisski_core\WisskiEntityViewsData",

You can savely delete this line. After that, the wisski_core module 
should install without errors.

The line installs a handler for Drupal views integration. However, 
WissKI entities do currently not integrate with views, as views still 
requires data to be stored in standard SQL db, and does neither support 
other db types, e.g. RDF triple stores, nor Drupal8's entity query.

Interesting enough, my Drupal test system installs the modules without 
complaining. We will fix this in the next commits nonetheless.


Am 24.01.2017 um 15:42 schrieb Sebastian Gassner:

**Comment by sepastian** [comment]
Thank you, that helped.

But I also had to replace all instances of `use Drupal\Component\Utility\String` with `use Drupal\Component\Utility\SafeMarkup` to make this run in PHP 7 in these files:

```
wisski_pathbuilder/src/Controller/WisskiPathListBuilder.php
wisski_pathbuilder/src/Controller/WisskiPathbuilderController.php
```
